const x = 10;


try {
    x = 2
} catch(err) {
    console.log(`Erro ao tentar atribuir valor a vari√°vel x: ${err}`)
}